# Generated by Django 3.2.5 on 2021-07-29 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedEvent',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coordenada', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user_agent', models.TextField(blank=True)),
                ('reported_hash', hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True, prefix='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
